# ClusterEnsemble demonstration
Some example usage of how to build up a dataframe of galaxy cluster properties, where each cluster is treated as an individual. This may be useful for fitting a stacked weak lensing profile, for example, where you want to avoid fitting a single average cluster mass and redshift.

In [1]:
import numpy as np
from clusters import ClusterEnsemble

%load_ext autoreload
%autoreload 2

### Create a ClusterEnsemble object by passing in a numpy array (or list) of redshifts

In [2]:
z = np.array([0.1,0.2,0.3])
c = ClusterEnsemble(z)
c.describe

'Ensemble of galaxy clusters and their properties.'

### Display what we have so far
Below the DataFrame, we see the default assumptions for the power-law slope and normalization that are used to convert richness $N_{200}$ to mass $M_{200}$. Soon we'll see how to change those parameters.

In [3]:
c.show()


Cluster Ensemble:


z
0  0.1
1  0.2
2  0.3


Mass-Richness Power Law: M200 = norm * N200^slope
   norm: 2.7e+13
   slope: 1.4


### Add richness values to the dataframe
This step will also generate $M_{200}$, $r_{200}$, $c_{200}$, and scale radius $r_s$, assuming the scaling relation given below.

In [4]:
n200 = np.array([20.,20.,20.])
c.update_richness(n200)
c.show()


Cluster Ensemble:


z  n200          m200          r200      c200            rs
0  0.1    20  1.789805e+15  6.079311e+13  3.852960  1.577829e+13
1  0.2    20  1.789805e+15  5.869395e+13  3.765176  1.558863e+13
2  0.3    20  1.789805e+15  5.654833e+13  3.670508  1.540613e+13


Mass-Richness Power Law: M200 = norm * N200^slope
   norm: 2.7e+13
   slope: 1.4


### Access any column of the dataframe as an array
Notice that units are present for the appropriate columns.

In [5]:
print c.z
print c.n200
print c.r200
print c.m200
print c.c200
print c.rs

[ 0.1  0.2  0.3]
[ 20.  20.  20.]
[  6.07931071e+13   5.86939457e+13   5.65483305e+13] cm / g(1/3)
[  1.78980517e+15   1.78980517e+15   1.78980517e+15]
[ 3.85295976  3.76517588  3.67050787]
[  1.57782876e+13   1.55886332e+13   1.54061324e+13] cm / g(1/3)


### Change the redshifts or richness values
These changes will propogate to all redshift-dependant or richness-dependant cluster attributes, as appropriate.

In [6]:
c.update_z(np.array([0.4,0.5,0.6]))
c.show()


Cluster Ensemble:


z  n200          m200          r200      c200            rs
0  0.4    20  1.789805e+15  5.439874e+13  3.576091  1.521179e+13
1  0.5    20  1.789805e+15  5.227930e+13  3.485412  1.499946e+13
2  0.6    20  1.789805e+15  5.021565e+13  3.400334  1.476786e+13


Mass-Richness Power Law: M200 = norm * N200^slope
   norm: 2.7e+13
   slope: 1.4


In [7]:
c.update_richness(np.array([20,30,40]))
c.show()


Cluster Ensemble:


z  n200          m200          r200      c200            rs
0  0.4    20  1.789805e+15  5.439874e+13  3.576091  1.521179e+13
1  0.5    30  3.157428e+15  6.316925e+13  3.315582  1.905224e+13
2  0.6    40  4.723324e+15  6.939365e+13  3.129900  2.217120e+13


Mass-Richness Power Law: M200 = norm * N200^slope
   norm: 2.7e+13
   slope: 1.4


### Change the parameters in the mass-richness relation
Either or both of the parameters "slope" and "norm" can be passed to the update_massrichrelation() method.

In [8]:
c.update_massrichrelation(slope = 1.5)
c.show()


Cluster Ensemble:


z  n200          m200          r200      c200            rs
0  0.4    20  2.414953e+15  6.011135e+13  3.480336  1.727171e+13
1  0.5    30  4.436553e+15  7.075271e+13  3.217815  2.198781e+13
2  0.6    40  6.830520e+15  7.847327e+13  3.032836  2.587455e+13


Mass-Richness Power Law: M200 = norm * N200^slope
   norm: 2.7e+13
   slope: 1.5


### Show basic table
Perhaps we don't want the fancy pandas formatting on our table, or maybe we're not working in the Jupyter notebook.

In [9]:
c.show(notebook = False)


Cluster Ensemble:
     z  n200          m200          r200      c200            rs
0  0.4    20  2.414953e+15  6.011135e+13  3.480336  1.727171e+13
1  0.5    30  4.436553e+15  7.075271e+13  3.217815  2.198781e+13
2  0.6    40  6.830520e+15  7.847327e+13  3.032836  2.587455e+13

Mass-Richness Power Law: M200 = norm * N200^slope
   norm: 2.7e+13
   slope: 1.5
